In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/Dataset1.csv")

df.head()

,circlename,regionname,divisionname,officename,pincode,officetype,delivery,district,statename,latitude,longitude
0,Telangana Circle,Hyderabad Region,Adilabad Division,Kothimir B.O,504273,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.3638689,79.5376658
1,Telangana Circle,Hyderabad Region,Adilabad Division,Papanpet B.O,504299,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.4764899,79.583923
2,Telangana Circle,Hyderabad Region,Adilabad Division,Kukuda B.O,504299,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,NaN,NaN
3,Telangana Circle,Hyderabad Region,Adilabad Division,Bareguda B.O,504296,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.3285752,79.4760132
4,Telangana Circle,Hyderabad Region,Adilabad Division,Mosam B.O,504296,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.3778044,79.6165209

In [2]:
df.shape

(165627, 11)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 165627 entries, 0 to 165626
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   circlename    165627 non-null  str
 1   regionname    165312 non-null  str
 2   divisionname  165627 non-null  str
 3   officename    165627 non-null  str
 4   pincode       165627 non-null  int64
 5   officetype    165627 non-null  str
 6   delivery      165627 non-null  str
 7   district      164912 non-null  str
 8   statename     164912 non-null  str
 9   latitude      153620 non-null  str
 10  longitude     153625 non-null  str
dtypes: int64(1), str(10)
memory usage: 13.9 MB

In [4]:
df.isnull().sum()

circlename          0
regionname        315
divisionname        0
officename          0
pincode             0
officetype          0
delivery            0
district          715
statename         715
latitude        12007
longitude       12002
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(2)

In [6]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
circlename,165627,24,Uttar Pradesh Circle,17997,NaN,NaN,NaN,NaN,NaN,NaN,NaN
regionname,165312,52,DivReportingCircle,30777,NaN,NaN,NaN,NaN,NaN,NaN,NaN
divisionname,165627,482,Bastar Division,1598,NaN,NaN,NaN,NaN,NaN,NaN,NaN
officename,165627,145086,Rampur BO,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pincode,165627.0,NaN,NaN,NaN,506840.727333,207001.361694,110001.0,341301.0,503180.0,690504.5,900099.0
officetype,165627,3,BO,140270,NaN,NaN,NaN,NaN,NaN,NaN,NaN
delivery,165627,2,Delivery,157901,NaN,NaN,NaN,NaN,NaN,NaN,NaN
district,164912,749,Y.S.R.,819,NaN,NaN,NaN,NaN,NaN,NaN,NaN
statename,164912,36,UTTAR PRADESH,17968,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latitude,153620,97762,15.5934,840,NaN,NaN,NaN,NaN,NaN,NaN,NaN
longitude,153625,91733,1,434,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df["officetype"].value_counts()

officetype
BO    140270
PO     24546
HO       811
Name: count, dtype: int64

In [8]:
df["delivery"].value_counts()

delivery
Delivery        157901
Non Delivery      7726
Name: count, dtype: int64

In [9]:
print("Unique PIN codes:", df["pincode"].nunique())
print("Unique states:", df["statename"].nunique())
print("Unique districts:", df["district"].nunique())
print("Unique offices:", df["officename"].nunique())

Unique PIN codes: 19586
Unique states: 36
Unique districts: 749
Unique offices: 145086

In [10]:
df[["latitude", "longitude"]].head(10)

     latitude   longitude
0  19.3638689  79.5376658
1  19.4764899   79.583923
2         NaN         NaN
3  19.3285752  79.4760132
4  19.3778044  79.6165209
5   19.240236  79.8205696
6  18.8730283  79.4118699
7   19.345435  79.4782916
8         NaN         NaN
9   19.182086  79.4816378

In [11]:
df["pincode"].astype(str).str.len().value_counts().sort_index()

pincode
6    165627
Name: count, dtype: int64

In [12]:
pincode_str = df["pincode"].astype(str)

df[
    (pincode_str.str.len() != 6) |
    (~pincode_str.str.isnumeric())
][["officename", "pincode", "district", "statename"]].head(20)

Empty DataFrame
Columns: [officename, pincode, district, statename]
Index: []

In [13]:
df[df.duplicated(keep=False)].sort_values(
    by=["officename", "pincode"]
)

,circlename,regionname,divisionname,officename,pincode,officetype,delivery,district,statename,latitude,longitude
14286,Madhya Pradesh Circle,DivReportingCircle,Vidisha Division,Bankhedi B.O,464573,BO,Delivery,RAISEN,MADHYA PRADESH,22.769054,78.534856
148131,Madhya Pradesh Circle,DivReportingCircle,Vidisha Division,Bankhedi B.O,464573,BO,Delivery,RAISEN,MADHYA PRADESH,22.769054,78.534856
15952,Maharashtra Circle,Navi Mumbai Region,Malegaon Division,Talwade B.O,423101,BO,Delivery,NASHIK,MAHARASHTRA,20.329957,74.24379
77166,Maharashtra Circle,Navi Mumbai Region,Malegaon Division,Talwade B.O,423101,BO,Delivery,NASHIK,MAHARASHTRA,20.329957,74.24379

In [14]:
df.duplicated(
    subset=["officename", "pincode"]
).sum()

np.int64(24)

In [15]:
print(df["latitude"].dtype)
print(df["longitude"].dtype)

str
str

In [16]:
duplicate_office_pin = df[
    df.duplicated(subset=["officename", "pincode"], keep=False)
].sort_values(["officename", "pincode"])

duplicate_office_pin

,circlename,regionname,divisionname,officename,pincode,officetype,delivery,district,statename,latitude,longitude
14286,Madhya Pradesh Circle,DivReportingCircle,Vidisha Division,Bankhedi B.O,464573,BO,Delivery,RAISEN,MADHYA PRADESH,22.769054,78.534856
148131,Madhya Pradesh Circle,DivReportingCircle,Vidisha Division,Bankhedi B.O,464573,BO,Delivery,RAISEN,MADHYA PRADESH,22.769054,78.534856
27799,Uttar Pradesh Circle,Agra Region,Aligarh Division,Bazidpur BO,250611,BO,Delivery,ALIGARH,UTTAR PRADESH,30.9418906,76.3789219
157177,Uttar Pradesh Circle,Bareilly Region,Baghpat Division,Bazidpur BO,250611,BO,Delivery,BAGHPAT,UTTAR PRADESH,29.1,77.3
92224,Uttar Pradesh Circle,Lucknow HQ Region,Faizabad Division,Bhupatipur BO,224122,BO,Delivery,AMBEDKAR NAGAR,UTTAR PRADESH,26.350214,83.058958
123932,Uttar Pradesh Circle,Bareilly Region,Kheri Division,Bhupatipur BO,224122,BO,Delivery,AMBEDKAR NAGAR,UTTAR PRADESH,27.7,80.69
71625,Bihar Circle,NaN,Nalanda Division,Daniyawan SO,801308,PO,Delivery,NALANDA,BIHAR,25.437668,85.35051
161449,Bihar Circle,NaN,Nalanda Division,Daniyawan SO,801308,PO,Delivery,NaN,NaN,25.43 N,85.29 E
60012,Uttar Pradesh Circle,Agra Region,Aligarh Division,Dariyapur BO,203001,BO,Delivery,HATHRAS,UTTAR PRADESH,27.6530262,78.1378503
60056,Uttar Pradesh Circle,Agra Region,Bulandshahar Division,Dariyapur BO,203001,BO,Delivery,BULANDSHAHR,UTTAR PRADESH,28.4227246,77.8002722
122728,Uttar Pradesh Circle,Agra Region,Aligarh Division,Datawali BO,283203,BO,Delivery,ALIGARH,UTTAR PRADESH,28.5114895,77.5691064
123048,Uttar Pradesh Circle,Agra Region,Mainpuri Division,Datawali BO,283203,BO,Delivery,FIROZABAD,UTTAR PRADESH,24.896596,79.355652
72255,Jharkhand Circle,DivReportingCircle,Santhal Parganas Division,Dumaria,814103,BO,Delivery,DUMKA,JHARKHAND,24.441223,87.40982
138415,Jharkhand Circle,DivReportingCircle,Santhal Parganas Division,Dumaria,814103,BO,Delivery,DUMKA,JHARKHAND,24.459644,87.429442
30984,Uttar Pradesh Circle,Lucknow HQ Region,Lucknow GPO Division,Gomti Nagar Extension SO Lucknow,226010,PO,Non Delivery,NaN,NaN,26.867149,81.003078
65130,Uttar Pradesh Circle,Lucknow HQ Region,Lucknow Division,Gomti Nagar Extension SO Lucknow,226010,PO,Non Delivery,LUCKNOW,UTTAR PRADESH,NaN,NaN
18027,North Eastern Circle,Shillong HQ Region,Arunachal Pradesh Division,Luchi,791122,BO,Delivery,UPPER SUBANSIRI,ARUNACHAL PRADESH,28.737963,94.219612
86312,North Eastern Circle,Shillong HQ Region,Arunachal Pradesh Division,Luchi,791122,BO,Delivery,UPPER SUBANSIRI,ARUNACHAL PRADESH,28.121529,94.2631153
68290,Telangana Circle,Hyderabad Region,Nizamabad Division,MAMIDIPALLI B.O,503003,BO,Delivery,NIZAMABAD,TELANGANA,18.7770697,78.2959965
69152,Telangana Circle,Hyderabad Region,Nizamabad Division,MAMIDIPALLI B.O,503003,BO,Delivery,NIZAMABAD,TELANGANA,18.7422993,78.1739044
69234,Telangana Circle,Hyderabad City Region,Sangareddy Division,Madharam B.O,509320,BO,Delivery,SANGAREDDY,TELANGANA,17.586236,78.311549
69910,Telangana Circle,Hyderabad Region,Wanaparthy Division,Madharam B.O,509320,BO,Delivery,NAGARKURNOOL,TELANGANA,NaN,NaN
47877,Kerala Circle,Calicut Region,Cannanore Division,Munderi BO,670591,BO,Delivery,KANNUR,KERALA,11.932713,75.4378581
110661,Kerala Circle,Calicut Region,Manjeri Division,Munderi BO,670591,BO,Delivery,KANNUR,KERALA,11.4432765,76.2590759
81115,Kerala Circle,Calicut Region,Calicut Division,Pakkom BO,673579,BO,Delivery,WAYANAD,KERALA,11.8,76.08
81174,Kerala Circle,Calicut Region,Kasaragod Division,Pakkom BO,673579,BO,Delivery,KASARAGOD,KERALA,12.39694,75.03425
110708,Kerala Circle,Calicut Region,Ottapalam Division,Panayur BO,679522,BO,Delivery,PALAKKAD,KERALA,15.5934,75.9995
110742,Kerala Circle,Calicut Region,Palghat Division,Panayur BO,679522,BO,Delivery,PALAKKAD,KERALA,15.5934,75.9995
150610,Odisha Circle,Berhampur Region,Rayagada Division,Penta B.O,765019,BO,Delivery,RAYAGADA,ODISHA,NaN,NaN
150620,Odisha Circle,Berhampur Region,Rayagada Division,Penta B.O,765019,BO,Delivery,RAYAGADA,ODISHA,19.7106516,83.4565116
50956,Odisha Circle,Bhubaneswar HQ Region,Balasore Division,Purusottampur B.O,754223,BO,Delivery,BALESHWAR,ODISHA,21.7163316,87.3557916
118187,Odisha Circle,Bhubaneswar HQ Region,KENDRAPARA DIVISION,Purusottampur B.O,754223,BO,Delivery,KENDRAPARA,ODISHA,20.485995,86.400539
90170,Uttar Pradesh Circle,Agra Region,Mathura Division,Raipur BO,209863,BO,Delivery,MATHURA,UTTAR PRADESH,27.47,77.69
155005,Uttar Pradesh Circle,Kanpur Region,Kanpur Moffusil Division,Raipur BO,209863,BO,Delivery,UNNAO,UTTAR PRADESH,26.255167,80.670515
90147,Uttar Pradesh Circle,Agra Region,Mathura Division,Sakatpur BO,241001,BO,Delivery,MATHURA,UTTAR PRADESH,27.47,77.69
123794,Uttar Pradesh Circle,Bareilly Region,Hardoi Division,Sakatpur BO,241001,BO,Delivery,HARDOI,UTTAR PRADESH,27.423,80.043
122708,Uttar Pradesh Circle,Agra Region,Aligarh Division,Salempur BO,203001,BO,Delivery,HATHRAS,UTTAR PRADESH,27.7457306,77.9225885
122748,Uttar Pradesh Circle,Agra Region,Bulandshahar Division,Salempur BO,203001,BO,Delivery,BULANDSHAHR,UTTAR PRADESH,28.3198475,77.9514259
123925,Uttar Pradesh Circle,Bareilly Region,Kheri Division,Sujanpur BO,262907,BO,Delivery,KHERI,UTTAR PRADESH,28.17,81.06
159138,Uttar Pradesh Circle,Agra Region,Aligarh Division,Sujanpur BO,262907,BO,Delivery,ALIGARH,UTTAR PRADESH,27.9734,77.7696
47438,Maharashtra Circle,Regional Office Aurangabad,Chhatrapati Sambhajinagar Division,Talegaon B.O,431807,BO,Delivery,AURANGABAD,MAHARASHTRA,19.876165,75.343314
77246,Maharashtra Circle,Regional Office Aurangabad,Nanded Division,Talegaon B.O,431807,BO,Delivery,NANDED,MAHARASHTRA,19.412184,77.604385
15952,Maharashtra Circle,Navi Mumbai Region,Malegaon Division,Talwade B.O,423101,BO,Delivery,NASHIK,MAHARASHTRA,20.329957,74.24379
77166,Maharashtra Circle,Navi Mumbai Region,Malegaon Division,Talwade B.O,423101,BO,Delivery,NASHIK,MAHARASHTRA,20.329957,74.24379
81249,Kerala Circle,Calicut Region,Manjeri Division,Valiyaparamba BO,673572,BO,Delivery,MALAPPURAM,KERALA,12.151,75.142
147021,Kerala Circle,Calicut Region,Calicut Division,Valiyaparamba BO,673572,BO,Delivery,KOZHIKODE,KERALA,11.4,75.9
110639,Kerala Circle,Calicut Region,Manjeri Division,Vengad BO,670612,BO,Delivery,MALAPPURAM,KERALA,11.880378,75.536404
114473,Kerala Circle,Calicut Region,Cannanore Division,Vengad BO,670612,BO,Delivery,KANNUR,KERALA,11.8761493,75.5386018

In [17]:
duplicate_office_pin[
    [
        "circlename",
        "regionname",
        "divisionname",
        "officename",
        "pincode",
        "officetype",
        "delivery",
        "district",
        "statename",
        "latitude",
        "longitude"
    ]
]

,circlename,regionname,divisionname,officename,pincode,officetype,delivery,district,statename,latitude,longitude
14286,Madhya Pradesh Circle,DivReportingCircle,Vidisha Division,Bankhedi B.O,464573,BO,Delivery,RAISEN,MADHYA PRADESH,22.769054,78.534856
148131,Madhya Pradesh Circle,DivReportingCircle,Vidisha Division,Bankhedi B.O,464573,BO,Delivery,RAISEN,MADHYA PRADESH,22.769054,78.534856
27799,Uttar Pradesh Circle,Agra Region,Aligarh Division,Bazidpur BO,250611,BO,Delivery,ALIGARH,UTTAR PRADESH,30.9418906,76.3789219
157177,Uttar Pradesh Circle,Bareilly Region,Baghpat Division,Bazidpur BO,250611,BO,Delivery,BAGHPAT,UTTAR PRADESH,29.1,77.3
92224,Uttar Pradesh Circle,Lucknow HQ Region,Faizabad Division,Bhupatipur BO,224122,BO,Delivery,AMBEDKAR NAGAR,UTTAR PRADESH,26.350214,83.058958
123932,Uttar Pradesh Circle,Bareilly Region,Kheri Division,Bhupatipur BO,224122,BO,Delivery,AMBEDKAR NAGAR,UTTAR PRADESH,27.7,80.69
71625,Bihar Circle,NaN,Nalanda Division,Daniyawan SO,801308,PO,Delivery,NALANDA,BIHAR,25.437668,85.35051
161449,Bihar Circle,NaN,Nalanda Division,Daniyawan SO,801308,PO,Delivery,NaN,NaN,25.43 N,85.29 E
60012,Uttar Pradesh Circle,Agra Region,Aligarh Division,Dariyapur BO,203001,BO,Delivery,HATHRAS,UTTAR PRADESH,27.6530262,78.1378503
60056,Uttar Pradesh Circle,Agra Region,Bulandshahar Division,Dariyapur BO,203001,BO,Delivery,BULANDSHAHR,UTTAR PRADESH,28.4227246,77.8002722
122728,Uttar Pradesh Circle,Agra Region,Aligarh Division,Datawali BO,283203,BO,Delivery,ALIGARH,UTTAR PRADESH,28.5114895,77.5691064
123048,Uttar Pradesh Circle,Agra Region,Mainpuri Division,Datawali BO,283203,BO,Delivery,FIROZABAD,UTTAR PRADESH,24.896596,79.355652
72255,Jharkhand Circle,DivReportingCircle,Santhal Parganas Division,Dumaria,814103,BO,Delivery,DUMKA,JHARKHAND,24.441223,87.40982
138415,Jharkhand Circle,DivReportingCircle,Santhal Parganas Division,Dumaria,814103,BO,Delivery,DUMKA,JHARKHAND,24.459644,87.429442
30984,Uttar Pradesh Circle,Lucknow HQ Region,Lucknow GPO Division,Gomti Nagar Extension SO Lucknow,226010,PO,Non Delivery,NaN,NaN,26.867149,81.003078
65130,Uttar Pradesh Circle,Lucknow HQ Region,Lucknow Division,Gomti Nagar Extension SO Lucknow,226010,PO,Non Delivery,LUCKNOW,UTTAR PRADESH,NaN,NaN
18027,North Eastern Circle,Shillong HQ Region,Arunachal Pradesh Division,Luchi,791122,BO,Delivery,UPPER SUBANSIRI,ARUNACHAL PRADESH,28.737963,94.219612
86312,North Eastern Circle,Shillong HQ Region,Arunachal Pradesh Division,Luchi,791122,BO,Delivery,UPPER SUBANSIRI,ARUNACHAL PRADESH,28.121529,94.2631153
68290,Telangana Circle,Hyderabad Region,Nizamabad Division,MAMIDIPALLI B.O,503003,BO,Delivery,NIZAMABAD,TELANGANA,18.7770697,78.2959965
69152,Telangana Circle,Hyderabad Region,Nizamabad Division,MAMIDIPALLI B.O,503003,BO,Delivery,NIZAMABAD,TELANGANA,18.7422993,78.1739044
69234,Telangana Circle,Hyderabad City Region,Sangareddy Division,Madharam B.O,509320,BO,Delivery,SANGAREDDY,TELANGANA,17.586236,78.311549
69910,Telangana Circle,Hyderabad Region,Wanaparthy Division,Madharam B.O,509320,BO,Delivery,NAGARKURNOOL,TELANGANA,NaN,NaN
47877,Kerala Circle,Calicut Region,Cannanore Division,Munderi BO,670591,BO,Delivery,KANNUR,KERALA,11.932713,75.4378581
110661,Kerala Circle,Calicut Region,Manjeri Division,Munderi BO,670591,BO,Delivery,KANNUR,KERALA,11.4432765,76.2590759
81115,Kerala Circle,Calicut Region,Calicut Division,Pakkom BO,673579,BO,Delivery,WAYANAD,KERALA,11.8,76.08
81174,Kerala Circle,Calicut Region,Kasaragod Division,Pakkom BO,673579,BO,Delivery,KASARAGOD,KERALA,12.39694,75.03425
110708,Kerala Circle,Calicut Region,Ottapalam Division,Panayur BO,679522,BO,Delivery,PALAKKAD,KERALA,15.5934,75.9995
110742,Kerala Circle,Calicut Region,Palghat Division,Panayur BO,679522,BO,Delivery,PALAKKAD,KERALA,15.5934,75.9995
150610,Odisha Circle,Berhampur Region,Rayagada Division,Penta B.O,765019,BO,Delivery,RAYAGADA,ODISHA,NaN,NaN
150620,Odisha Circle,Berhampur Region,Rayagada Division,Penta B.O,765019,BO,Delivery,RAYAGADA,ODISHA,19.7106516,83.4565116
50956,Odisha Circle,Bhubaneswar HQ Region,Balasore Division,Purusottampur B.O,754223,BO,Delivery,BALESHWAR,ODISHA,21.7163316,87.3557916
118187,Odisha Circle,Bhubaneswar HQ Region,KENDRAPARA DIVISION,Purusottampur B.O,754223,BO,Delivery,KENDRAPARA,ODISHA,20.485995,86.400539
90170,Uttar Pradesh Circle,Agra Region,Mathura Division,Raipur BO,209863,BO,Delivery,MATHURA,UTTAR PRADESH,27.47,77.69
155005,Uttar Pradesh Circle,Kanpur Region,Kanpur Moffusil Division,Raipur BO,209863,BO,Delivery,UNNAO,UTTAR PRADESH,26.255167,80.670515
90147,Uttar Pradesh Circle,Agra Region,Mathura Division,Sakatpur BO,241001,BO,Delivery,MATHURA,UTTAR PRADESH,27.47,77.69
123794,Uttar Pradesh Circle,Bareilly Region,Hardoi Division,Sakatpur BO,241001,BO,Delivery,HARDOI,UTTAR PRADESH,27.423,80.043
122708,Uttar Pradesh Circle,Agra Region,Aligarh Division,Salempur BO,203001,BO,Delivery,HATHRAS,UTTAR PRADESH,27.7457306,77.9225885
122748,Uttar Pradesh Circle,Agra Region,Bulandshahar Division,Salempur BO,203001,BO,Delivery,BULANDSHAHR,UTTAR PRADESH,28.3198475,77.9514259
123925,Uttar Pradesh Circle,Bareilly Region,Kheri Division,Sujanpur BO,262907,BO,Delivery,KHERI,UTTAR PRADESH,28.17,81.06
159138,Uttar Pradesh Circle,Agra Region,Aligarh Division,Sujanpur BO,262907,BO,Delivery,ALIGARH,UTTAR PRADESH,27.9734,77.7696
47438,Maharashtra Circle,Regional Office Aurangabad,Chhatrapati Sambhajinagar Division,Talegaon B.O,431807,BO,Delivery,AURANGABAD,MAHARASHTRA,19.876165,75.343314
77246,Maharashtra Circle,Regional Office Aurangabad,Nanded Division,Talegaon B.O,431807,BO,Delivery,NANDED,MAHARASHTRA,19.412184,77.604385
15952,Maharashtra Circle,Navi Mumbai Region,Malegaon Division,Talwade B.O,423101,BO,Delivery,NASHIK,MAHARASHTRA,20.329957,74.24379
77166,Maharashtra Circle,Navi Mumbai Region,Malegaon Division,Talwade B.O,423101,BO,Delivery,NASHIK,MAHARASHTRA,20.329957,74.24379
81249,Kerala Circle,Calicut Region,Manjeri Division,Valiyaparamba BO,673572,BO,Delivery,MALAPPURAM,KERALA,12.151,75.142
147021,Kerala Circle,Calicut Region,Calicut Division,Valiyaparamba BO,673572,BO,Delivery,KOZHIKODE,KERALA,11.4,75.9
110639,Kerala Circle,Calicut Region,Manjeri Division,Vengad BO,670612,BO,Delivery,MALAPPURAM,KERALA,11.880378,75.536404
114473,Kerala Circle,Calicut Region,Cannanore Division,Vengad BO,670612,BO,Delivery,KANNUR,KERALA,11.8761493,75.5386018

In [18]:
df["latitude_num"] = pd.to_numeric(df["latitude"], errors="coerce")
df["longitude_num"] = pd.to_numeric(df["longitude"], errors="coerce")

print("Invalid/missing latitude:", df["latitude_num"].isna().sum())
print("Invalid/missing longitude:", df["longitude_num"].isna().sum())

Invalid/missing latitude: 12013
Invalid/missing longitude: 12008

In [19]:
print("Latitude range:")
print(df["latitude_num"].min(), df["latitude_num"].max())

print("\nLongitude range:")
print(df["longitude_num"].min(), df["longitude_num"].max())

Latitude range:
0.0 233643145.0

Longitude range:
0.0 9334975723.0

In [20]:
df.loc[
    df["latitude_num"] > 90,
    ["officename", "pincode", "district", "statename", "latitude", "longitude"]
].head(20)

,officename,pincode,district,statename,latitude,longitude
4808,Aideopukhuri B.O,785690,CHARAIDEO,ASSAM,94.6318889,26.9886944
7094,Udari BO,497101,SURGUJA,CHHATTISGARH,23724.29,832015.52
7354,Bachhunchh BO,171207,SHIMLA,HIMACHAL PRADESH,331.2,77.752
7634,Hardtour BO,192201,ANANTNAG,JAMMU AND KASHMIR,129.6,72.4
7635,Hiller Arahama BO,192201,ANANTNAG,JAMMU AND KASHMIR,129.6,72.36
7636,Litter BO,192305,PULWAMA,JAMMU AND KASHMIR,129.6,72.4
7637,Wasoora BO,192305,PULWAMA,JAMMU AND KASHMIR,129.6,112.6
7639,Naina BO,192124,ANANTNAG,JAMMU AND KASHMIR,123.6,72.4
7647,Hiller Shahabad BO,192211,ANANTNAG,JAMMU AND KASHMIR,256.2,284.2
7656,Malwan BO,192231,KULGAM,JAMMU AND KASHMIR,132.5,195.3
7662,Pingliana BO,192301,PULWAMA,JAMMU AND KASHMIR,125.8,123.9
7663,Tahaba Shadipora BO,192301,PULWAMA,JAMMU AND KASHMIR,132.5,195.3
7672,Kathsoo BO,192401,ANANTNAG,JAMMU AND KASHMIR,325,12.5
7676,Dadsar BO,192123,PULWAMA,JAMMU AND KASHMIR,225.3,137.5
7677,Lurgam BO,192123,PULWAMA,JAMMU AND KASHMIR,134.6,74.5
7678,Saimoh BO,192123,PULWAMA,JAMMU AND KASHMIR,124.5,74.6
7679,Nowgam BO,192212,ANANTNAG,JAMMU AND KASHMIR,132,123.9
7680,Reban Gund BO,192232,SHOPIAN,JAMMU AND KASHMIR,235.6,90.2
7681,Chanthan Checkpora BO,193411,Budgam,JAMMU AND KASHMIR,119.6,95.36
7682,Chewdarah BO,193411,Budgam,JAMMU AND KASHMIR,115.2,72.63

In [21]:
df.loc[
    df["longitude_num"] > 180,
    ["officename", "pincode", "district", "statename", "latitude", "longitude"]
].head(20)

,officename,pincode,district,statename,latitude,longitude
7094,Udari BO,497101,SURGUJA,CHHATTISGARH,23724.29,832015.52
7647,Hiller Shahabad BO,192211,ANANTNAG,JAMMU AND KASHMIR,256.2,284.2
7656,Malwan BO,192231,KULGAM,JAMMU AND KASHMIR,132.5,195.3
7663,Tahaba Shadipora BO,192301,PULWAMA,JAMMU AND KASHMIR,132.5,195.3
7689,Rangar BO,191113,Budgam,JAMMU AND KASHMIR,2154.2,3256.1
14570,Dhakochi B.O,450117,EAST NIMAR,MADHYA PRADESH,21.7935739,767971247
15707,Kuslamb B.O,413207,BEED,MAHARASHTRA,18.859012,75371206
21107,Sulawas B.O,313706,UDAIPUR,RAJASTHAN,24.42,740.06
41611,Kattepura B.O,573130,HASSAN,KARNATAKA,12.61,7605
42616,Nellow BO,192231,KULGAM,JAMMU AND KASHMIR,125.9,361.2
42630,Bargam BO,192123,PULWAMA,JAMMU AND KASHMIR,235.3,2536.2
42657,Hajibal BO,193402,BARAMULLA,JAMMU AND KASHMIR,153.9,245.7
44279,Umri(J) B.O,431713,NANDED,MAHARASHTRA,19.365789,77646804
44490,Kolha B.O,431505,PARBHANI,MAHARASHTRA,19.391691,76553492
44784,PODSA B.O,442702,CHANDRAPUR,MAHARASHTRA,19.51,7958
51643,Sonajuli B.O,791123,PAPUM PARE,ARUNACHAL PRADESH,27.0389962,7506694076
55412,Kahinagar BO,731219,BIRBHUM,WEST BENGAL,24.449306,887.825501
59476,Athur B.O,609204,MAYILADUTHURAI,TAMIL NADU,11.16,793.53
74599,Pahaloo BO,192231,KULGAM,JAMMU AND KASHMIR,132,256.3
74603,Newa BO,192301,PULWAMA,JAMMU AND KASHMIR,125.8,195.3

In [22]:
df.loc[
    (df["latitude_num"] == 0) | (df["longitude_num"] == 0),
    ["officename", "pincode", "district", "statename", "latitude", "longitude"]
].head(20)

,officename,pincode,district,statename,latitude,longitude
29772,D Block South City II Gurgaon,122018,GURUGRAM,HARYANA,0,0
34356,Sahawada B.O,494336,RAIPUR,CHHATTISGARH,0,0
37632,Om Nagar B.O,518313,KURNOOL,ANDHRA PRADESH,0,0
70463,Nagaladinne B.O,518343,KURNOOL,ANDHRA PRADESH,0,0
70465,Peddakothali B.O,518343,KURNOOL,ANDHRA PRADESH,0,0
76014,Nathianawagaon B.O,494336,RAIPUR,CHHATTISGARH,0,0
101115,Udkuda B.O,494336,RAIPUR,CHHATTISGARH,0,0
104807,Singvad SO,389135,DOHAD,GUJARAT,0,0
104808,Lokikere S.O,577009,DAVANGERE,KARNATAKA,0,0
134122,Tarasgaon B.O,494336,RAIPUR,CHHATTISGARH,0,0
134123,Tuyegahan B.O,494336,RAIPUR,CHHATTISGARH,0,0
137530,Chinnathumbalam B.O,518313,KURNOOL,ANDHRA PRADESH,0,0
137531,Malapalli B.O,518313,KURNOOL,ANDHRA PRADESH,0,0

In [23]:
df.loc[
    (df["latitude_num"] < 6) | (df["latitude_num"] > 37) |
    (df["longitude_num"] < 68) | (df["longitude_num"] > 98),
    ["officename", "pincode", "district", "statename", "latitude", "longitude"]
].head(30)

,officename,pincode,district,statename,latitude,longitude
46,Kasimpalli B.O,506169,JAYASHANKAR BHUPALAPALLY,TELANGANA,79,17
47,Laxmareddipalli B.O,506168,JAYASHANKAR BHUPALAPALLY,TELANGANA,35.8968,61.25369
48,Garimillapalli B.O,506356,JAYASHANKAR BHUPALAPALLY,TELANGANA,39.5698,58.6359
365,Yellareddypalli B.O,503164,NIZAMABAD,TELANGANA,18.1690283,18.1690283
686,Chilakalapalli B.O,535557,Parvathipuram Manyam,ANDHRA PRADESH,83.5297,18.6149
689,Vengapuram Agraharam B.O,535557,Parvathipuram Manyam,ANDHRA PRADESH,83.5183,18.6153
690,Mirthivalasa B.O,535559,Parvathipuram Manyam,ANDHRA PRADESH,83.4133,18.5267
691,Bondapalli B.O,535128,VIZIANAGARAM,ANDHRA PRADESH,83.6018,18.37
692,Badangi B.O,535578,VIZIANAGARAM,ANDHRA PRADESH,83.3531,18.4836
693,Pappala Lingalavalasa B.O,535578,VIZIANAGARAM,ANDHRA PRADESH,83.3531,18.4836
694,Bhyripuram B.O,535102,VIZIANAGARAM,ANDHRA PRADESH,83.4409,18.3558
695,Mokhasa Lingalavalasa B.O,535102,VIZIANAGARAM,ANDHRA PRADESH,83.4629,18.4109
696,Bangaruvalasa B.O,535547,Parvathipuram Manyam,ANDHRA PRADESH,83.2637,18.6913
697,Markondaputti B.O,535547,Parvathipuram Manyam,ANDHRA PRADESH,83.2286,18.6906
698,Saraivalasa B.O,535547,Parvathipuram Manyam,ANDHRA PRADESH,83.2509,18.6889
699,Chemudu B.O,535547,Parvathipuram Manyam,ANDHRA PRADESH,83.2178,18.6294
700,Lakshmipuram B.O,535547,Parvathipuram Manyam,ANDHRA PRADESH,83.4092,18.6609
701,Kottuparuva B.O,535593,Parvathipuram Manyam,ANDHRA PRADESH,83.1569,18.6444
702,Kurukutti B.O,535593,Parvathipuram Manyam,ANDHRA PRADESH,83.0936,18.5901
703,Sivili Peddavalasa B.O,535593,Parvathipuram Manyam,ANDHRA PRADESH,83.2107,18.6544
704,Devarapodilam B.O,535125,VIZIANAGARAM,ANDHRA PRADESH,83.6135,18.3299
705,Nimmalavalasa B.O,535125,VIZIANAGARAM,ANDHRA PRADESH,83.6818,18.3049
706,Palavalasa B.O,535125,VIZIANAGARAM,ANDHRA PRADESH,83.6747,18.2708
707,Karrivalasa B.O,535592,Parvathipuram Manyam,ANDHRA PRADESH,83.102,18.4546
708,Padmapuram B.O,535592,Parvathipuram Manyam,ANDHRA PRADESH,83.0957,18.4828
709,Nandabalaga B.O,535568,VIZIANAGARAM,ANDHRA PRADESH,83.4706,18.5439
710,Pinapenki B.O,535568,VIZIANAGARAM,ANDHRA PRADESH,83.4529,18.5322
711,Paradi B.O,503321,VIZIANAGARAM,ANDHRA PRADESH,83.3069,18.523
712,Patharega B.O,535579,VIZIANAGARAM,ANDHRA PRADESH,83.3006,18.4263
713,Korapukothavalasa B.O,535579,VIZIANAGARAM,ANDHRA PRADESH,83.2647,18.4549

In [25]:
# Convert coordinates to numeric
df["latitude_num"] = pd.to_numeric(df["latitude"], errors="coerce")
df["longitude_num"] = pd.to_numeric(df["longitude"], errors="coerce")

# Valid approximate geographic bounds for India
valid_lat = df["latitude_num"].between(6, 38)
valid_lon = df["longitude_num"].between(68, 98)

# 1. Normal coordinates
normal = valid_lat & valid_lon

# 2. Strong candidates for reversed coordinates
reversed_coords = (
    df["latitude_num"].between(68, 98) &
    df["longitude_num"].between(6, 38)
)

# 3. Missing or zero coordinates
missing_or_zero = (
    df["latitude_num"].isna() |
    df["longitude_num"].isna() |
    (df["latitude_num"] == 0) |
    (df["longitude_num"] == 0)
)

# 4. Other invalid/corrupted coordinates
invalid = ~(normal | reversed_coords | missing_or_zero)

# Results
print("Normal:", normal.sum())
print("Potentially reversed:", reversed_coords.sum())
print("Missing/zero:", missing_or_zero.sum())
print("Other invalid/corrupted:", invalid.sum())

print("\nTotal:", len(df))
print(
    "Check:",
    normal.sum()
    + reversed_coords.sum()
    + missing_or_zero.sum()
    + invalid.sum()
)

Normal: 151010
Potentially reversed: 791
Missing/zero: 12028
Other invalid/corrupted: 1798

Total: 165627
Check: 165627

In [26]:
processed_df = pd.read_csv("../data/processed/postal_network.csv")

print("Shape:", processed_df.shape)

Shape: (165625, 11)

In [27]:
processed_df.isnull().sum()

circlename          0
regionname        315
divisionname        0
officename          0
pincode             0
officetype          0
delivery            0
district          715
statename         715
latitude        13826
longitude       13826
dtype: int64

In [28]:
processed_df[["latitude", "longitude"]].describe()

            latitude      longitude
count  151799.000000  151799.000000
mean       21.773938      80.004543
std         5.844798       5.318160
min         6.332500      68.010000
25%        17.826352      76.134968
50%        22.698900      78.956794
75%        26.219591      83.552976
max        37.832300      97.810000

In [29]:
processed_df.head()

,circlename,regionname,divisionname,officename,pincode,officetype,delivery,district,statename,latitude,longitude
0,Telangana Circle,Hyderabad Region,Adilabad Division,Kothimir B.O,504273,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.363869,79.537666
1,Telangana Circle,Hyderabad Region,Adilabad Division,Papanpet B.O,504299,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.476490,79.583923
2,Telangana Circle,Hyderabad Region,Adilabad Division,Kukuda B.O,504299,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,NaN,NaN
3,Telangana Circle,Hyderabad Region,Adilabad Division,Bareguda B.O,504296,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.328575,79.476013
4,Telangana Circle,Hyderabad Region,Adilabad Division,Mosam B.O,504296,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.377804,79.616521